### ISSUE TITLE
Hangup and Failed Downloads

### ISSUE THREAD

**Issue by Jonesckevin** [digitalsleuth/winfor-salt#32]
**Using the download button provides me the following failed download and does not continue:**

```log
2025-05-27 22:52:57,142 [tornado.general  :1382][WARNING ][21260] SSL Error on 2344 ('35.161.100.221', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
2025-05-27 22:52:57,142 [asyncio          :1758][ERROR   ][21260] Exception in callback _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669
handle: <Handle _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669>
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 669, in <lambda>
    fut.add_done_callback(lambda f: final_callback(f.result()))
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "C:\Program Files\Salt Project\Salt\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
```

Once I remove this from being checked, I have other failed attempt to download:
```log
----------
          ID: download-only-states
    Function: test.nop
      Result: False
     Comment: One or more requisite failed: winfor.downloads.packages.active-disk-editor.active-disk-editor-download-only, winfor.downloads.packages.pdfstreamdumper.pdfstreamdumper-download-only, winfor.downloads.standalones.hibernation-recon.hiber-recon-download-only, winfor.downloads.packages.bulkrenameutility.bulkrenameutility-download-only, winfor.downloads.packages.eventlog-explorer.eventlog-explorer-download-only, winfor.downloads.packages.tableau-firmware-update.tableau-firmware-update-download-only, winfor.downloads.packages.resource-hacker.resource-hacker-download-only, winfor.downloads.packages.db-browser-sqlite.db-browser-sqlite-download-only, winfor.downloads.packages.wiebetech-writeblocking-validation-utility.wiebetech-writeblocking-validation-utility-download-only, winfor.downloads.standalones.srum-dump2.srum-dump2-template-download-only, winfor.downloads.standalones.scdbg.scdbg-download-only, winfor.downloads.packages.tableau-imager.tableau-imager-download-only, winfor.downloads.packages.agentransack.agentransack-download-only, winfor.downloads.packages.dotnet6-desktop-runtime.dotnet6-desktop-runtime-download-only, winfor.downloads.standalones.srum-dump2.srum-dump2-fget-download-only, winfor.downloads.standalones.pilfer.pilfer-download-only, winfor.downloads.packages.ms-vcpp-2015-build-tools.ms-vcpp-2015-build-tools-download-only, winfor.downloads.packages.android-studio.android-studio-download-only, winfor.downloads.standalones.total-pe-2.total-pe-2-download-only
     Started: 23:16:19.249114
    Duration: 0.0 ms
     Changes:   

Summary for local
--------------
Succeeded: 297 (changed=135)
Failed:     20
--------------
Total states run:     317
Total run time:  1187.655 s
```

## Errors only:

```log
2025-05-27 22:52:41,905 [salt.state       :320 ][ERROR   ][21260] Specified sha256 checksum for D:\Tools\Downloads\active-disk-editor\diskeditor-freeware-24.exe (e6a25c5ccc73994c46c43bc9e56bd872a486b1843d01de7510001d594e17917b) does not match actual checksum (8df270147ea1cc4a4c516c280d288ea19a131ad771d32280ffa41deb01c88e73)
2025-05-27 22:52:43,576 [salt.state       :320 ][ERROR   ][21260] Failed to cache https://download.mythicsoft.com/flp/3435/agentransack_x64_msi_3435.zip: Error: HTTP 403: Forbidden reading /flp/3435/agentransack_x64_msi_3435.zip
2025-05-27 22:52:48,177 [salt.state       :320 ][ERROR   ][21260] Specified sha256 checksum for D:\Tools\Downloads\bulk-rename-utility\BRU_setup_4.0.0.3.exe (69a3fae1566b06f75be4ac5b2a813488b475230e32879191990895a3ce81fa0e) does not match actual checksum (c70d2e20e777c1d215fc6a80f27f43da6eff26da4383425b1e65e209e0b99a31)
2025-05-27 22:52:55,278 [salt.state       :320 ][ERROR   ][21260] Specified sha256 checksum for D:\Tools\Downloads\dotnet6-desktop-runtime\windowsdesktop-runtime-6.0.36-win-x64.exe (d669f26726fd40649f21613b6289c29f6329fd9242f8e4af4f979cc8f4f92739) does not match actual checksum (0d20debb26fc8b2bc84f25fbd9d4596a6364af8517ebf012e8b871127b798941)
2025-05-27 22:52:57,142 [asyncio          :1758][ERROR   ][21260] Exception in callback _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669
2025-05-27 22:56:36,781 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\active-disk-editor\diskeditor-freeware-24.exe (e6a25c5ccc73994c46c43bc9e56bd872a486b1843d01de7510001d594e17917b) does not match actual checksum (8df270147ea1cc4a4c516c280d288ea19a131ad771d32280ffa41deb01c88e73)
2025-05-27 22:56:37,699 [salt.state       :320 ][ERROR   ][19588] Failed to cache https://download.mythicsoft.com/flp/3435/agentransack_x64_msi_3435.zip: Error: HTTP 403: Forbidden reading /flp/3435/agentransack_x64_msi_3435.zip
2025-05-27 22:56:41,896 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\bulk-rename-utility\BRU_setup_4.0.0.3.exe (69a3fae1566b06f75be4ac5b2a813488b475230e32879191990895a3ce81fa0e) does not match actual checksum (c70d2e20e777c1d215fc6a80f27f43da6eff26da4383425b1e65e209e0b99a31)
2025-05-27 22:56:49,000 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\dotnet6-desktop-runtime\windowsdesktop-runtime-6.0.36-win-x64.exe (d669f26726fd40649f21613b6289c29f6329fd9242f8e4af4f979cc8f4f92739) does not match actual checksum (0d20debb26fc8b2bc84f25fbd9d4596a6364af8517ebf012e8b871127b798941)
2025-05-27 22:56:50,529 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\eventlog-explorer\elex_setup-5.6.exe (c66638722f2012138b2bfa8c8095658e5bd8b5c2659e294b5d9b425e3513d333) does not match actual checksum (5049c96130396f407197a74fa571f10e4106bd0c13858e717fc11c535fded678)
2025-05-27 22:58:21,316 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\ms-vcpp\vcpp-2015-buildtools-15.9.34749.27.exe (4a89c5ebe6ce816e2020f31214a3dec20cdd25142245bc344a7a1b82af4d0907) does not match actual checksum (2d67b51649f2f576aee4ae349df6ffa31acdb2643138d589b5e3cdbad949306d)
2025-05-27 22:58:36,927 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\resource-hacker\reshacker_setup-5.2.6.exe (246457363396dcea4cc3d19ce2a431897bac948ae1694d3e87cc0ebaf2ea39f5) does not match actual checksum (b611be2f35cb44efd1c29df03e7ebe62bd556a500585680e1afa5e073eaf1756)
2025-05-27 22:59:42,161 [salt.state       :320 ][ERROR   ][19588] Failed to cache https://wiebetech.com/downloads/1395/WbValUtil-2.1.1.0-(2024.05.14)-x64.exe: Error: HTTP 504: Gateway Timeout reading /downloads/1395/WbValUtil-2.1.1.0-(2024.05.14)-x64.exe
2025-05-27 23:11:42,713 [salt.loaded.int.module.cmdmod:948 ][ERROR   ][19588] Command 'D:\Tools\Downloads\megatools\megatools\megatools.exe' failed with return code: 1
2025-05-27 23:11:42,713 [salt.loaded.int.module.cmdmod:952 ][ERROR   ][19588] stderr: ERROR: Download failed for 'https://mega.nz/file/z4Q2iD4C#1I8eFUnuV-x-OOuFJ7G-8YWcNPDfrV26w3aL2mnqGPI': API call 'g' failed: Server returned error ENOENT
2025-05-27 23:11:42,714 [salt.loaded.int.module.cmdmod:954 ][ERROR   ][19588] retcode: 1
2025-05-27 23:11:42,714 [salt.state       :320 ][ERROR   ][19588] {'pid': 13400, 'retcode': 1, 'stdout': '', 'stderr': "ERROR: Download failed for 'https://mega.nz/file/z4Q2iD4C#1I8eFUnuV-x-OOuFJ7G-8YWcNPDfrV26w3aL2mnqGPI': API call 'g' failed: Server returned error ENOENT"}
2025-05-27 23:14:13,139 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\pilfer\pilfer-3.4.bat (9d6ca8ea5e1a25d35e7eed2f9c1557bfbbd4eb202bec45aac01d462315a34b1e) does not match actual checksum (60b3e10664f3cefb397514dc290c078ea0e11129008c0d85967eb38df792efba)
2025-05-27 23:14:24,073 [salt.state       :320 ][ERROR   ][19588] Failed to cache https://github.com/MarkBaggett/srum-dump/raw/master/SRUM_TEMPLATE3.xlsx: Error: HTTP 404: Not Found reading /MarkBaggett/srum-dump/raw/master/SRUM_TEMPLATE3.xlsx
2025-05-27 23:14:24,375 [salt.state       :320 ][ERROR   ][19588] Failed to cache https://github.com/MarkBaggett/srum-dump/raw/master/FGET.exe: Error: HTTP 404: Not Found reading /MarkBaggett/srum-dump/raw/master/FGET.exe
2025-05-27 23:14:44,176 [salt.state       :320 ][ERROR   ][19588] Specified sha256 checksum for D:\Tools\Downloads\total-pe-2\TotalPE.exe (c0c2af261f8b4e47be845ce6740fa2d51b9baa4731795a22b7ed46a4b84ecdc0) does not match actual checksum (265bf06eb5e14e5ee2e2a2b261215b914f3885fe543873a1c97795decd89e03e)

```

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , I'm still trying to identify the elcomsoft download issue from [this issue](https://github.com/digitalsleuth/WIN-FOR/issues/13) and should have a resolution for that by tomorrow. As for the others, it looks like there are newer versions, so I will adjust for the newer versions this evening and submit a new release.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , I've come up with a workaround for the Elcomsoft package issue and will release a new state release tonight. However, you will need a [new version of the Win-FOR installer](https://github.com/digitalsleuth/WIN-FOR/releases) in order to download / install the packages, as this new release addresses a bug/fix in the last version of SaltStack.

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , this should be fixed now. Please make sure you also use the updates Win-FOR installer going forward, especially if you plan on using Windows 11.

Cheers!

**Comment by Jonesckevin** [comment]
I have downloaded the `winfor-customizer-v10.1.0`, and I do still get a SSL certificate issue. The host is Windows 11 as well.

![Image](https://github.com/user-attachments/assets/119e34e2-c5e4-4463-b701-f2b48149bd49)

**Version before your recent update push**
```log
2025-05-29 22:18:35,220 [tornado.general  :1382][WARNING ][15776] SSL Error on 1696 ('35.161.100.221', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
2025-05-29 22:18:35,221 [asyncio          :1758][ERROR   ][15776] Exception in callback _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669
handle: <Handle _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669>
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 669, in <lambda>
    fut.add_done_callback(lambda f: final_callback(f.result()))
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "C:\Program Files\Salt Project\Salt\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
```

**Recent attempt**
```log
2025-05-29 22:40:21,372 [tornado.general  :1382][WARNING ][19448] SSL Error on 2292 ('35.161.100.221', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
2025-05-29 22:40:21,375 [asyncio          :1758][ERROR   ][19448] Exception in callback _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669
handle: <Handle _HTTPConnection.finish.<locals>.<lambda>(<Future finis...ssl.c:1017)")>) at C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py:669>
Traceback (most recent call last):
  File "C:\Program Files\Salt Project\Salt\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 669, in <lambda>
    fut.add_done_callback(lambda f: final_callback(f.result()))
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\simple_httpclient.py", line 340, in run
    stream = await self.tcp_client.connect(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\tcpclient.py", line 292, in connect
    stream = await stream.start_tls(
  File "C:\Program Files\Salt Project\Salt\Lib\site-packages\tornado\iostream.py", line 1367, in _do_ssl_handshake
    self.socket.do_handshake()
  File "C:\Program Files\Salt Project\Salt\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'download_us.elcomsoft.com'. (_ssl.c:1017)
```

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , looks like one of my modifications didn't get copied over before my last push. I'll fix that as soon as I get in later this evening.

**Comment by digitalsleuth** [comment]
There you go @Jonesckevin , it's fixed now.

**Comment by Jonesckevin** [comment]
It works for me now.

I did however still get these errors:
```log
2025-05-31 22:32:25,082 [salt.state       :320 ][ERROR   ][6516] Failed to cache https://redirector.gvt1.com/edgedl/android/studio/install/2024.3.2.15/android-studio-2024.3.2.15-windows.exe: Error: [Errno 11004] getaddrinfo failed reading /edgedl/android/studio/install/2024.3.2.15/android-studio-2024.3.2.15-windows.exe
2025-05-31 22:34:22,783 [salt.state       :320 ][ERROR   ][6516] Invalid length (40) for hash type 'sha256'. Either remove the hash type and simply use '00abac84773a33728d57100a7e900e62376ccffa' as the source_hash, or change the hash type to 'sha1'
2025-05-31 22:37:09,066 [salt.state       :320 ][ERROR   ][6516] Failed to cache http://sandsprite.com/CodeStuff/PDFStreamDumper_Setup.exe: Error: [Errno 11004] getaddrinfo failed reading /CodeStuff/PDFStreamDumper_Setup.exe
2025-05-31 22:37:13,432 [salt.state       :320 ][ERROR   ][6516] Failed to cache https://mimage.opentext.com/support/ecm/tableau/setup_tableau_firmware_update_24.3.msi: Error: [Errno 11004] getaddrinfo failed reading /support/ecm/tableau/setup_tableau_firmware_update_24.3.msi
2025-05-31 22:37:13,447 [salt.state       :320 ][ERROR   ][6516] Failed to cache https://mimage.opentext.com/support/ecm/tableau/setup_tableau_imager_20.3.msi: Error: [Errno 11004] getaddrinfo failed reading /support/ecm/tableau/setup_tableau_imager_20.3.msi
2025-05-31 22:38:40,121 [salt.state       :320 ][ERROR   ][6516] Failed to cache http://sandsprite.com/CodeStuff/scdbg.zip: Error: [Errno 11004] getaddrinfo failed reading /CodeStuff/scdbg.zip
```
```log
     Comment: One or more requisite failed: winfor.downloads.packages.tableau-imager.tableau-imager-download-only, winfor.downloads.packages.pdfstreamdumper.pdfstreamdumper-download-only, winfor.downloads.standalones.scdbg.scdbg-download-only, winfor.downloads.packages.tableau-firmware-update.tableau-firmware-update-download-only, winfor.downloads.packages.eventlog-explorer.eventlog-explorer-download-only, winfor.downloads.packages.android-studio.android-studio-download-only


--------------
Succeeded: 309 (changed=309)
Failed:      7
--------------
```

**Comment by digitalsleuth** [comment]
Any time you see a `getaddrinfo` error, that means that your connection has dropped, so you've temporarily lost connectivity. So you may need to try again for those with that error. Can you though provide me the lines surrounding the error `[ERROR   ][6516] Invalid length (40) for hash type 'sha256'`. If that's an incorrect hash value in the state, then that needs to be fixed on my end.

**Comment by digitalsleuth** [comment]
Nevermind, I found it. I'll add that fix to the next release.

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , this should be fixed now with the latest release. Cheers!
